### PR TITLE
Add background image replacement crop & resize tool

### LINKED ISSUE #122: Add BG crop/resize tool
A nice-to-have would be something that lets you crop/resize background images rather than just force resizing the image/aspect ratio down like we do currently.

### PR DESCRIPTION
**Pull request by WiIIiam278**
Closes #122 

Adds a UI for resizing and cropping background images.

You can drag the image around, use ctrl+scroll to quickly scale, and use the arrowkeys to (or use the UI to do these things). 

There's also a function for auto-scaling and resetting the image position, and it tracks the aspect ratio to make scaling a bit less painful.

<details>
<summary>Screenshots</summary>

image
image
image
</details>

Might still need a bit of code cleanup / tweaks here and there -- but feel free to review

### CODE REVIEW

**Comment by jonko0493** [comment]
This is so good!!

After testing on Windows, I have two notes:
* On Windows, the image does not show up until you attempt to resize it
* I would like for the Ctrl+Scroll & arrow keys controls to be documented in the window itself so that it's obvious those can be used

**Comment by jonko0493** [comment]
Same issues apply to Linux.

**Comment by WiIIiam278** [comment]
Should be fixed

**Comment by jonko0493** [comment]
Is fixed, but now one more issue:
image
the buttons are off the screen

**Review by jonko0493 — APPROVED** [review]
Fantastic work. Let's merge it :)

**Pull request merged**
