### PR TITLE
Add the scenario editor to the Avalonia branch

### PR DESCRIPTION
**Pull request by jonko0493**
Yay it's back in! This lays the groundwork for the script editor, so that's also great!

### CODE REVIEW

**Comment by Dazawassa** [comment]
If you add a command on the scenario editor it causes the program to close. I tested on Linux Mint 22. That was the only thing that stood out. Everything else worked as intended. I ran the program from command line and added a command. Below is the output I got.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SerialLoops.ViewModels.Editors.ScenarioEditorViewModel.Add() in /home/darcy/Documents/Git/PR_check/SerialLoops/src/SerialLoops/ViewModels/Editors/ScenarioEditorViewModel.cs:line 82
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at SerialLoops.Program.Main(String[] args) in /home/darcy/Documents/Git/PR_check/SerialLoops/src/SerialLoops/Program.cs:line 13
Aborted (core dumped)

I would have made it a code block but doing that removed some symbols,

**Comment by jonko0493** [comment]
@Dazawassa can you tell me more details? Did you have a command selected when you hit the add button? Which command did you attempt to add?

**Comment by Dazawassa** [comment]
> @Dazawassa can you tell me more details? Did you have a command selected when you hit the add button? Which command did you attempt to add?

I tried "SAVE2" and "NEW_GAWE". I didn't test every option. Interestingly if you open the dialogue box to add a command and then cancel the program closes anyway.

**Comment by jonko0493** [comment]
Bug fixed in latest push.

**Review by WiIIiam278 — APPROVED** [review]
Builds fine, can't repro Dazawassa's bug, so looks good :)

**Pull request merged**
